project:
  title: "MetabolicAnalytics-Apps.github.io"
  type: website
  output-dir: _site
  resources: 
  - shinylive-sw.js
  - Test_App.html  # Fügen Sie Ihre HTML-App als Ressource hinzu
  
execute:
  engine: knitr

website:
  title: "ShinyApps"
  page-navigation: true
  page-footer:
    right: "[Quarto](https://quarto.org/)"
    left: "Johannes Will, 2025 | [JohannesWill96@gmail.com](mailto:JohannesWill96@gmail.com)"
      
  sidebar:
    logo: "images/Logo_1.png"
    pinned: false
    align: center
    style: "docked"
    search: true
    collapse-level: 3 #Ab welchem Level die Unterpunkt nicht mehr angezeigt werden. Bei 2 wird bspw. bei Energieumsatz die Unterpunkte eingeklappt
    contents:
       - about.qmd
       - section: Metabolic_Model_Apps/index_Metabolic_Model_Apps.qmd
         contents:
           - section: Metabolic_Model_Apps/Power_Profile/Power_Profile.qmd
             contents:
              - Metabolic_Model_Apps/Power_Profile/Etalon_Calculator.qmd         
           - Metabolic_Model_Apps/Metabolic_Profile.qmd
           - Metabolic_Model_Apps/Mader_Modell.qmd
       - section: Cycling_Apps/index_Cycling_Apps.qmd
         contents: 
           - Cycling_Apps//Cycling_Forces.qmd
           - Cycling_Apps//CdA_App.qmd
       - Cadence_Test.qmd
       
lang: en
number-sections: true
bibliography: references.bib
csl: apa.csl
reference-section-title: "References"
format:
  html: 
    grid:
      sidebar-width: 200px
      body-width: 1350px
      margin-width: 50px
      gutter-width: 1rem
      
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
    css: styles.css
    toc: false
    # toc-expand: 3
    # toc-title: Inhalt auf dieser Seite
    # toc-location: right 

    code-fold: false
    code-tools: false
    code-copy: false
    code-overflow: wrap
    
    lightbox: true
    