---
title: "Sports Science Models & Applications"

execute:
  message: false
  engine: knitr
  echo: false
  warning: false
  error: false
---

```{css}
#| echo: false
p {
  text-align: justify
}
caption, .figure-caption {
  text-align: left;
}
figure.quarto-float-tbl figcaption {
  text-align: left !important;
}
figure figcaption {
  text-align: justify;
}
```

This website provides interactive sports science tools and applications for exercise physiology analysis. The collection includes models for metabolic calculations, performance predictions. Available applications help quantify physiological parameters and analyze the relationships between exercise intensity, metabolism, and athletic performance through evidence-based calculations and visual representations.

**Please note: This website is currently under construction.** I'm gradually adding more detailed explanations of the applications and developing additional models. The content will continue to expand over time.

For additional tools, take a look at the website I created for my [master's thesis](https://jjrw96.github.io/Wirkungsgrad-Rad.github.io/about.html). This site offers similar applications with comprehensive explanations, but comes in German only and centers on examining efficiency factors in cycling performance.

